### ISSUE TITLE
UK bus needs to move

### ISSUE THREAD

**Issue by keitkollo** [stevenbeeckman/stevenbeeckman.github.io#8]
![13324454_10153384473206157_1404164507_o](https://cloud.githubusercontent.com/assets/8867623/15726727/66b3aaea-284a-11e6-8c62-d48c7c894526.jpg)

Perhaps should be the 7th one rather than the 8th (so would look better on mobile).

**Comment by stevenbeeckman** [comment]
I have no idea on how to do this. Perhaps you do, @DonaldWhyte ?

**Comment by DonaldWhyte** [comment]
I can handle this. I'll probably make it a hack though -- use JS to detect when the resolution is mobile (i.e. 1 column) and just hide the two black boxes.

**Comment by DonaldWhyte** [comment]
Estonian bus has been removed, so this problem has gone away. Marking issue as resolved.
